### GetAll Categories
GET https://localhost:5001/Api/Users/All HTTP/1.1
content-type: application/json

### GetAll User OData
GET https://localhost:5001/Api/Users/All?$filter=Id eq 3
& $select=Name,Email HTTP/1.1
content-type: application/json

### Add User
POST https://localhost:5001/Api/Users/Add HTTP/1.1
content-type: application/json

{
    "Name" : "Jasmine",
    "Email" : "jasmine@abc.com",
    "IsAdmin" : false,
    "IsActive" : false
}

### Update User
PATCH https://localhost:5001/Api/Users/Update HTTP/1.1
content-type: application/json

{
    "Id" : 1,
    "Name" : "Jasmine Randhawa",
    "Email" : "jasminerandhawa7@abc.com",
    "IsAdmin" : true
}

### Deactivate User
PATCH https://localhost:5001/Api/Users/Deactivate/1 HTTP/1.1
content-type: application/json

### Activate User
PATCH https://localhost:5001/Api/Users/Activate/1 HTTP/1.1
content-type: application/json

###---------------------------------------------------------------------------------
### GetAll Categories
GET https://localhost:5001/Api/Categories/All HTTP/1.1
content-type: application/json

### GetAll Categorie OData
GET https://localhost:5001/Api/Categories/All?$filter=Id eq 1
& $select=Name,IsActive HTTP/1.1
content-type: application/json

### Add Category
POST https://localhost:5001/Api/Categories/Add HTTP/1.1
content-type: application/json

{
    "Name" : "SeaFood",
    "IsActive" : false
}

### Update Category
PUT https://localhost:5001/Api/Categories/Update HTTP/1.1
content-type: application/json

{
    "Id" : 8,
    "Name" : "SeaFood and Fish",
    "IsActive" : true
}

### Deactivate Category
PATCH https://localhost:5001/Api/Categories/Deactivate/8 HTTP/1.1
content-type: application/json

### Activate Category
PATCH https://localhost:5001/Api/Categories/Activate/8 HTTP/1.1
content-type: application/json

###---------------------------------------------------------------------------------
### GetAll Products
GET https://localhost:5001/Api/Products/All HTTP/1.1
content-type: application/json

### GetAll Product OData
GET https://localhost:5001/Api/Products/All?$filter=Id eq 1
& $select=Title,ImageURL HTTP/1.1
content-type: application/json

### Add Product
POST https://localhost:5001/Api/Products/Add HTTP/1.1
content-type: application/json

{
    "Title" : "Bread",
    "Price" : 1.9,
    "ImageURL" : "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Red_Apple.jpg/199px-Red_Apple.jpg",
    "CategoryId" : 1,
    "IsActive" : true
}

### Update Product
PUT https://localhost:5001/Api/Products/Update HTTP/1.1
content-type: application/json

{
    "Id" : 1,
    "Title" : "Green Apple",
     "Price" : 2.9,
    "ImageURL" : "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Red_Apple.jpg/199px-Red_Apple.jpg",
    "CategoryId" : 1,
    "IsActive" : false
}

### Deactivate Product
PATCH https://localhost:5001/Api/Products/Deactivate/1 HTTP/1.1
content-type: application/json

### Activate Product
PATCH https://localhost:5001/Api/Products/Activate/1 HTTP/1.1
content-type: application/json

###---------------------------------------------------------------------------------
### GetAll ShoppingCart By User
GET https://localhost:5001/Api/ShoppingCart/User/1 HTTP/1.1
content-type: application/json

### GetById ShoppingCart By Id
GET https://localhost:5001/Api/ShoppingCart/2 HTTP/1.1
content-type: application/json

### Add ShoppingCart
POST https://localhost:5001/Api/ShoppingCart/Add HTTP/1.1
content-type: application/json

{
    "AppUserId" : 1,
    "Items" : [
        {
            "ProductId" : 3,
            "Quantity" : 5
        }
    ]
}

### Update ShoppingCart
PATCH https://localhost:5001/Api/ShoppingCart/Update HTTP/1.1
content-type: application/json

{
    "Id" : 2,
    "AppUserId" : 1,
    "Items" : [
        {
            "ProductId" : 1,
            "Quantity" : 2
        },
        {
            "ProductId" : 2,
            "Quantity" : 3
        }
    ]
}

### Delete ShoppingCart
DELETE https://localhost:5001/Api/ShoppingCart/1 HTTP/1.1
content-type: application/json

###---------------------------------------------------------------------------------
### GetAll Orders By User
GET https://localhost:5001/Api/Orders/User/1 HTTP/1.1
content-type: application/json

### GetById Order By Id
GET https://localhost:5001/Api/Orders/1 HTTP/1.1
content-type: application/json

### Add Order
POST https://localhost:5001/Api/Orders/Add HTTP/1.1
content-type: application/json

{
    "ShoppingCartId" : 2,
    "UserName" :"Jasmine",
    "Address" : "Edmonton",
    "AppUserId" : 1
}

### Delete Order
DELETE https://localhost:5001/Api/Orders/1 HTTP/1.1
content-type: application/json
###---------------------------------------------------------------------------------