### GetAll Users
GET https://localhost:5001/Api/Users/All HTTP/1.1
content-type: application/json

### GetById User
GET https://localhost:5001/Api/Users/1 HTTP/1.1
content-type: application/json

### Add User
POST https://localhost:5001/Api/Users/Add HTTP/1.1
content-type: application/json

{
    "Name" : "Jasmine",
    "Email" : "jasmine@abc.com",
    "IsAdmin" : false,
    "IsActive" : false
}

### Update User
PATCH https://localhost:5001/Api/Users/Update HTTP/1.1
content-type: application/json

{
    "Id" : 1,
    "Name" : "Jasmine Randhawa",
    "Email" : "jasminerandhawa@abc.com",
    "IsAdmin" : true
}

### Deactivate User
PATCH https://localhost:5001/Api/Users/Deactivate/1 HTTP/1.1
content-type: application/json

### Activate User
PATCH https://localhost:5001/Api/Users/Activate/1 HTTP/1.1
content-type: application/json

###---------------------------------------------------------------------------------
### GetAll Categories
GET https://localhost:5001/Api/Categories/All HTTP/1.1
content-type: application/json

### GetById Category
GET https://localhost:5001/Api/Categories/8 HTTP/1.1
content-type: application/json

### Add Category
POST https://localhost:5001/Api/Categories/Add HTTP/1.1
content-type: application/json

{
    "Name" : "SeaFood",
    "IsActive" : false
}

### Update Category
PUT https://localhost:5001/Api/Categories/Update HTTP/1.1
content-type: application/json

{
    "Id" : 8,
    "Name" : "SeaFood and Fish",
    "IsActive" : true
}

### Deactivate Category
PATCH https://localhost:5001/Api/Categories/Deactivate/8 HTTP/1.1
content-type: application/json

### Activate Category
PATCH https://localhost:5001/Api/Categories/Activate/8 HTTP/1.1
content-type: application/json

###---------------------------------------------------------------------------------
### GetAll Products
GET https://localhost:5001/Api/Products/All HTTP/1.1
content-type: application/json

### GetById Product
GET https://localhost:5001/Api/Products/1 HTTP/1.1
content-type: application/json

### Add Product
POST https://localhost:5001/Api/Products/Add HTTP/1.1
content-type: application/json

{
    "Title" : "Bread",
    "ImageURL" : "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Red_Apple.jpg/199px-Red_Apple.jpg",
    "CategoryId" : 1,
    "IsActive" : true
}

### Update Product
PUT https://localhost:5001/Api/Products/Update HTTP/1.1
content-type: application/json

{
    "Id" : 1,
    "Title" : "Green Apple",
    "ImageURL" : "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Red_Apple.jpg/199px-Red_Apple.jpg",
    "CategoryId" : 1,
    "IsActive" : false
}

### Deactivate Product
PATCH https://localhost:5001/Api/Products/Deactivate/1 HTTP/1.1
content-type: application/json

### Activate Product
PATCH https://localhost:5001/Api/Products/Activate/1 HTTP/1.1
content-type: application/json

###---------------------------------------------------------------------------------
### GetByUser ShoppingCart
GET https://localhost:5001/Api/ShoppingCart/User/1 HTTP/1.1
content-type: application/json

### GetById ShoppingCart
GET https://localhost:5001/Api/ShoppingCart/1 HTTP/1.1
content-type: application/json

### Add ShoppingCart
POST https://localhost:5001/Api/ShoppingCart/Add HTTP/1.1
content-type: application/json

{
    "AppUserId" : 1,
    "Items" : [
        {
            "ProductId" : 1,
            "Quantity" : 2
        }
    ]
}

### Update ShoppingCart
PATCH https://localhost:5001/Api/ShoppingCart/Update HTTP/1.1
content-type: application/json

{
    "Id" : 1,
    "AppUserId" : 1,
    "Items" : [
        {
            "ProductId" : 1,
            "Quantity" : 2
        },
        {
            "ProductId" : 2,
            "Quantity" : 3
        }
    ]
}

### Delete ShoppingCart
DELETE https://localhost:5001/Api/ShoppingCart/1 HTTP/1.1
content-type: application/json
